### ISSUE TITLE
Some ideas and suggestions when assembling UI to models

### ISSUE THREAD

**Issue by Ckang2021** [Mustard2/MustardUI#100]
Thank you very much for your excellent work in making the model available quickly with a wonderful UI panel control.

Here are some ideas I had while assembling the UI to the model:

## Multi-user use of Armature data

After the initial loading of the UI to the model, the Armature data of the Rig will be occupied by the UI, which will prevent a addon called [Auto IK Rigger](https://daitomodachi.gumroad.com/l/BszdI) from working properly because the Armature is used by multiple entities.

![blender_Bjil5kvbUX](https://user-images.githubusercontent.com/101509191/225298988-24fd0b8b-f570-4a16-8eb9-03d1c7754c82.jpg)
![blender_VLybqNK6tP](https://user-images.githubusercontent.com/101509191/225298994-d7c9f2ea-4979-4f9a-b04a-f5895da5c711.jpg)

My solution is to make a single-user copy and then go to the link lib and delete the original Armature data, then rebuilt in the UI (without testing if not rebuilding would have an effect on the model).

![blender_2KAwXwyLMJ](https://user-images.githubusercontent.com/101509191/225300220-014f876f-8327-4213-874d-0f19455172c5.jpg)

I'm not sure if this problem can be solved, although it's not a problem to clean up the Armature data.

---

The second one is whether it is possible to add support for curved hairs?

Currently I have replaced the particle hairs by curved hairs, but the UI is currently unable to control curved hairs through the hairs panel.

My current solution is to add it to the Outfits panel as an Extra props.

![image](https://user-images.githubusercontent.com/101509191/225301167-cfad4b5c-bddd-40f1-9de5-f3cea8c171e3.png)

If needed, my model can be found on Smutbase.

Thanks again for the excellent panel and look forward to your updates in the future.

**Comment by Mustard2** [comment]
Hi!

I'm aware of the problem of the two users on the armature, never actually thought it might create some issues. But since it does, I'll try to investigate it a bit more. Atm I'm not sure where in the code that problem arises to be honest.

For the others, sure! I was waiting for Blender to finalize the support for hair, but with 3.5 I guess it's time to properly add them to MustardUI. :)

Thanks again for the suggestions, and sorry for the late reply!

**Comment by Mustard2** [comment]
- [ ] Fix the Armature object duplicate error
- [ ] Introduce support to curved hairs

**Comment by Mustard2** [comment]
Hi @Ckang2021 , can you please check if the new version #106 is what you wanted?
I added curves hair as for particle hair, in the sense that they aren't on the list and thus they aren't mutually exclusive.

**Comment by Ckang2021** [comment]
Hi @Mustard2, praise for your hard work! After testing, I have identified some issues:

1. The Hair feature requires a meshes to be present in the Hair collection in order to activate. It cannot be used solely with curves hair.

![blender_W5sxEa9QPr](https://github.com/Mustard2/MustardUI/assets/101509191/a1f36cb1-e104-41b6-9ce1-8bd026cc29d4)
![blender_YD6BXkLTbN](https://github.com/Mustard2/MustardUI/assets/101509191/46f15966-2c2f-4a56-a8cd-e4dbe2273ecf)

2. Enabling meshes hair affects the usage of curves hair. When switching to any other meshes hair, the curves hair gets disabled.

After conducting some additional tests, I found that particle hair is also affected by the first issue mentioned, while the second issue does not affect it.

**Comment by Mustard2** [comment]
Hi @Ckang2021 , thanks for checking it. Now the two issues should be solved.

**Comment by Mustard2** [comment]
Now looking at your images, would you prefer to have the Char_name Hair removed from the name? Might be nicer I guess :)

**Comment by Ckang2021** [comment]
Thank you for the update. 

The switching of mesh hair no longer affects the display of curve hair, but the issue remains that mesh hair is still required to activate the hair functionality. Currently, my workaround is to include the Proxy Mesh in the hair collection but disable their visibility and rendering. However, this brings up a new issue where the toggle switch in the Hair List affects the entire collection, resulting in the curve hair not being displayed/rendered properly.

<div style="display:inline-block">
  <img src="https://github.com/Mustard2/MustardUI/assets/101509191/fcd87466-3270-49dd-80fc-2438a938b615" alt="img1" width="400">
  <img src="https://github.com/Mustard2/MustardUI/assets/101509191/1d8e726d-9f4a-419e-a5aa-5e5288908948" alt="img2" width="400">
</div>

**Comment by Mustard2** [comment]
@Ckang2021 Thank you very much for beta testing this and for the valuable feedbacks!

I updated the version again, hoping it works correctly now. Please let me know, and thank you again! :)

**Comment by Ckang2021** [comment]
Thanks for the recent update, the curve hair is now working properly, although it says "An error occurred", maybe I can add a model hair to avoid this problem? 

Is there a possibility to have mesh/curve/particle hair on equal footing so that they can coexist without conflicts and be freely combined?
(There is no real impact, but the console will keep printing errors)

![image](https://github.com/Mustard2/MustardUI/assets/101509191/13b10912-3bd8-41d6-ae6e-058e1538c795)

---

The second thing is that the display/render indicator for particle hairs seems to be the wrong icon, I looked at other designs and it only has a blue background when it is disabled.
(For comparison, I turned off Pubic hair as a reference)

![image](https://github.com/Mustard2/MustardUI/assets/101509191/632eff4a-b844-42ac-a0a2-012086d98737)

---

Thank you once again for the time and effort you have dedicated to this project. I hope it continues to improve. :D

**Comment by Mustard2** [comment]
Hi!

For the first issue, as it says, try to enter configuration mode and then exit it. That should solve the issue in principle.

As for the second, it's how Blender works unfortunately. In case of hair particles, the property is called show_particle, in the other case hide_object, so the blue "embossing" effect is different.

Let me know if you can fix the first issue clicking on the button Enter Configuration Mode!

**Comment by Ckang2021** [comment]
Hello, thank you for your explanation and response. I have tested it, but entering and exiting the configuration did not solve the issue.

At the same time, the error message `C:\Users\blender\git\blender-v350\blender.git\source\blender\python\intern\bpy_rna.c:1341 pyrna_enum_to_py: current value '0' matches no enum in 'MustardUI_RigSettings', '', 'hair_list'` is still being output when hovering over any component of the UI. I have tested renaming the hair collection and curve hair, but the issue persists. If you need more information or further testing, please let me know.

This is my test project, with all packed textures removed: https://files.catbox.moe/f5cyd7.blend (14.5MB)

**Comment by Mustard2** [comment]
Ok, you're right, there was another bug :(
Now it should be fixed, I hope :D

**Comment by Ckang2021** [comment]
@Mustard2 
New problems caused by multi-user use of Armature data:

Hello, in my recent modeling process, I accidentally assembled the UI before converting Daz armature to Rigify (Diffeomorphic) . 

Similarly, this will cause problems with automatic conversion. I need to separate the Armature data first, but this leads to a new problem: all models' Morph targets will be incorrect. 

The Morph targets are based on the original Armature data. I have tried mapping the data (which makes the newly separated Armature become multi-user use again), which means I cannot restore the data to a state without UI after assembling it again, even if I have uninstalled the UI.

Currently, my solution is to revert back to the project before I assembled the UI and restore the added content. Then, after assembling Rigify, I add the UI again. 

I'm not sure if I made a mistake at some point, but I have tested it myself and found that Morph can be used normally when it converting to Rigify without UI, If you need me to provide the project or more information, please let me know.

Thank you for your work. 🫡

**Comment by Mustard2** [comment]
Hi @Ckang2021 ! Sorry I missed this comment (I don't receive the notifications :( ).
Sure, if you have any blend file I can try to take a look at it.

**Comment by Mustard2** [comment]
Hi! Sorry after careful evaluation, unfortunately this seems to be a Blender limitation rather than something I could fix on my end.

As for the Diffeomorphic issue, it seems like the addon creators should support Armatures with multiple users (as in principle they should do, because beside this addon, many other functionalities might lead to multiple users on the armature data).

Please re-open this issue is specific problem arises again from this, for the moment I'm closing.
