### ISSUE TITLE
Can't activate the 0.30 MustardUI addon

### ISSUE THREAD

**Issue by IamTirion** [Mustard2/MustardUI#130]
**Describe the bug**
I can't activate the addon after installing it

**To Reproduce**
1. Open Blender 4.0
2. Download MustardUI 0.30
3. Install it
4. Click the checkbox
5. See the error

**Expected behavior**
I should be able to activate the addon after installing it.

**Screenshots**
![image](https://github.com/Mustard2/MustardUI/assets/50409752/e7f570cb-3efa-4251-883b-4511623a2378)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by Mustard2** [comment]
Can you try with this solution?

> I actually found a solution that worked for me in Blender 4.0. You need to run the program as administrator and then install the .zip.

Suggested by @KoreyMiracle

**Comment by IamTirion** [comment]
@Mustard2 The new version worked. As for the previous solution, I couldn't run Blender as administrator because there is no such option on Steam. Thank you.

**Comment by Mustard2** [comment]
Great!
I added a temporary fix which is not great, for some reasons it had some problems registering classes.

I'll wait for others to confirm (@mokujinh @adiolol11 @KoreyMiracle), if it's fixed for everyone I'll push the update. :)

**Comment by adiolol11** [comment]
Nope, for me doesnt work even as administrator

**Comment by Mustard2** [comment]
Sorry I'm trying different fixes, what about this? @adiolol11 

[MustardUI.zip](https://github.com/Mustard2/MustardUI/files/13355985/MustardUI.zip)

**Comment by adiolol11** [comment]
It works now , thanks a lot

**Comment by Mustard2** [comment]
Thanks for the patience and for trying!

**Comment by Mustard2** [comment]
Fixed by https://github.com/Mustard2/MustardUI/releases/tag/0.30.1

**Comment by kiss-hth** [comment]
> (Hopefully) fixed by https://github.com/Mustard2/MustardUI/releases/tag/0.30.1

Hi,It still doesn't work.To activate the MustardUI addon,I have to disable the addon before i close the blender and open the addon in ’Preferences‘ when i open my blender again 
If I forget Uncheck the addon ,it still doesn't work when i start again

**Comment by kiss-hth** [comment]
It works,but when i load a new model the bug still exist like this
![Problem1](https://github.com/Mustard2/MustardUI/assets/131333206/73c6c92c-7e0f-4087-a8d5-d3bb06439f2b)
So I have to restart my blender 4.0 and click the checkbox of the addon the bug is fixed like this
![problem2](https://github.com/Mustard2/MustardUI/assets/131333206/5a44104f-1550-430f-80f7-aecbf2d00a63)
So I speculate that the cause of the bug is a conflict between the data from the previous model and the existing data

**Comment by kiss-hth** [comment]
> @kiss-hth You have to remove all existing old mustard_ui.py (or any MustardUI script that is named differently, the UI now automatically deletes only the ones named correctly) scripts from the model (they're in the Text window), save the file and then close ALL Blender windows. Only then you can use the UI.
> 
> Note that if you open even just one model with the old script, that is loaded and it can bug the whole UI. Just be sure that whenever you load Blender, no model has the old script (that is, do the procedure above if they have one).

Amazing! The addon works well.
Thanks again for your help.
