### ISSUE TITLE
Old bone collections stuck in UI

### ISSUE THREAD

**Issue by J4ke6599** [Mustard2/MustardUI#159]
Basically when I redid my scene and wanted to import the same UI to the new scene, I forgot to delete the bone collections of the old armature from the UI.

The new armature has the same collections and bones as in the old UI, but when I delete them from the UI, it deletes the actual collections from the armature, starting with the first one on the list, but the collections remain in the UI. Also assigning the bones to them is totally bugged and creating new collections doesn't add them to the UI collections list. It's also showing some old collections that don't exist anymore and I can't remove them as it removes wrong collections.

Just wondering if there is a way to wipe the old stuff completely from the UI.

**Comment by J4ke6599** [comment]
Ah never mind about the collection add part, I didn't realize that you can make new bone collections within the UI, but still, the collection is showing old and missing ones and new collections aren't added to the list, only in the armature object data properties tab.

**Comment by Mustard2** [comment]
Uhm, do you have a screenshot of the issue? Because I'm not sure I understood what's happening

**Comment by Mustard2** [comment]
I pushed a new version, since there was an issue with the armature panel. Maybe it might fix also your issue, please let me know. :)

**Comment by J4ke6599** [comment]
Hey, the issue still persists. Also any new bone collections aren't even added to the UI for some reason. And I can't delete the ones added to the UI, it'll just remove them from the whole armature, but the collections remain in the UI.

**Comment by Mustard2** [comment]
> Hey, the issue still persists. Also any new bone collections aren't even added to the UI for some reason. And I can't delete the ones added to the UI, it'll just remove them from the whole armature, but the collections remain in the UI.

Please send me the blend file without textures, so I check what went wrong in the data structure of the armature.

**Comment by Mustard2** [comment]
Closing this as there was no new message. If the issue persists, please open a new one here. :)

**Comment by J4ke6599** [comment]
Hey, sorry for not responding earlier. I've been fixing some dependency issues (unrelated to this issue) and noticed that there are two instances of the armature my figure uses. Let's call the main armature A and the one the UI uses B.

If I select any bone in pose mode, there should a white dot visible on the collection that bone belongs to. Well, on armature A, nothing changes. When I in the Armature Object Data Properties tab switch the Armature Data from A to B, it switches the skeleton and I can't change the body. It also adds mustard custom properties.

Is it supposed to create a duplicate? Because I cannot add the proper armature A bone collections to armature B that is connected to the UI.

I'm also guessing that any custom properties I linked to UI are also linked to the duplicate armature B.
